name: preview
on:
  push:
    paths:
      - "apps/engagement-app/**"
      - ".github/workflows/*engagement*.yml"
    branches-ignore:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main
    paths:
      - "apps/engagement-app/**"
      - ".github/workflows/*engagement*.yml"
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - run: npm install --global turbo@latest
      - run: yarn install --immutable
      #get env vars
      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
        working-directory: apps/engagement-app
      - run: echo "$(node -v)"
      - run: vercel build --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
        working-directory: apps/engagement-app
      - id: deploy
        run: echo "::set-output name=url::$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_DEPLOY_TOKEN }})"
        working-directory: apps/engagement-app
